Repository riccardobertolini/lofi-music, pull requests merged in 2023-07, with the labels that each got.

#1 All dependencies were upgraded by ncu ⬆️.
  package-lock.json
  package.json
Labels: enhancement

#33 Implemented an Image component into the tile player, which now i…
  components/tilePlayer.tsx
Labels: enhancement

#41 Fixed problem with hydration of react player.
  components/tilePlayer.tsx
Labels: bug

#44 Fixed problem with naming of props in Styled Components
  components/tilePlayer.style.tsx
  components/tilePlayer.tsx
Labels: bug

#47 Added prefetch component for images
  components/PrefetchImages.tsx
  components/tilePlayer.style.tsx
  pages/index.js
Labels: bug

#55 added Color change option in settings
  components/SettingModal.style.tsx
  components/SettingModal.tsx
Labels: ready-for-review
